# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/app: 9b2c5234f57f3021e9b7186d7180f173a3a4bbe8b447e0976ef5b41a91bb7d31
    io.kubernetes.cri-o.SandboxID/db: 9b2c5234f57f3021e9b7186d7180f173a3a4bbe8b447e0976ef5b41a91bb7d31
  creationTimestamp: "2025-06-19T18:08:54Z"
  labels:
    app: wordpress
  name: wordpress
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MARIADB_PASSWORD
      value: w0rdpr3ss
    - name: NO_PROXY
      value: local,169.254/16
    - name: MARIADB_ROOT_PASSWORD
      value: passw0rd
    - name: MARIADB_DATABASE
      value: wordpress
    - name: MARIADB_USER
      value: wordpress
    image: docker.io/library/mariadb:lts-ubi
    name: db
    ports:
    - containerPort: 80
      hostPort: 80
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: 2d975932868848c9ff6d1bf5c9b2b17080b0aac9828b4ca0d5de0f94e923d94f-pvc
  - args:
    - apache2-foreground
    env:
    - name: NO_PROXY
      value: local,169.254/16
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: w0rdpr3ss
    - name: WORDPRESS_DB_HOST
      value: db
    - name: WORDPRESS_DB_NAME
      value: wordpress
    image: docker.io/library/wordpress:latest
    name: app
    volumeMounts:
    - mountPath: /var/www/html
      name: 74c0fc4d3a4fd00e76a40b4dc8a18d3f793b0ba56b2049b5a6d2f28110e3c675-pvc
  volumes:
  - name: 2d975932868848c9ff6d1bf5c9b2b17080b0aac9828b4ca0d5de0f94e923d94f-pvc
    persistentVolumeClaim:
      claimName: 2d975932868848c9ff6d1bf5c9b2b17080b0aac9828b4ca0d5de0f94e923d94f
  - name: 74c0fc4d3a4fd00e76a40b4dc8a18d3f793b0ba56b2049b5a6d2f28110e3c675-pvc
    persistentVolumeClaim:
      claimName: 74c0fc4d3a4fd00e76a40b4dc8a18d3f793b0ba56b2049b5a6d2f28110e3c675

