# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/db: b1272fb99a19b898a0b34711b15a62674b894607c6352d5c81344d7bcac0fb81
    io.kubernetes.cri-o.SandboxID/wordpress: b1272fb99a19b898a0b34711b15a62674b894607c6352d5c81344d7bcac0fb81
  creationTimestamp: "2025-06-19T18:00:27Z"
  labels:
    app: wordpress-pod
  name: wordpress-pod
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MARIADB_PASSWORD
      value: w0rdpr3ss
    - name: MARIADB_USER
      value: wordpress
    - name: MARIADB_ROOT_PASSWORD
      value: passw0rd
    - name: MARIADB_DATABASE
      value: wordpress
    - name: NO_PROXY
      value: local,169.254/16
    image: docker.io/library/mariadb:lts-ubi
    name: db
    ports:
    - containerPort: 80
      hostPort: 80
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: 982da85fd0bd6c7ffc6cbe399b68888033ebebb95bd7580d6768d3434b4288b6-pvc
  - args:
    - apache2-foreground
    env:
    - name: NO_PROXY
      value: local,169.254/16
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_HOST
      value: db
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: w0rdpr3ss
    image: docker.io/library/wordpress:latest
    name: wordpress
    volumeMounts:
    - mountPath: /var/www/html
      name: 85b442e55f8c1a847df7a75c2c964051ca5333af424a3b309aad5f82fb448be2-pvc
  volumes:
  - name: 982da85fd0bd6c7ffc6cbe399b68888033ebebb95bd7580d6768d3434b4288b6-pvc
    persistentVolumeClaim:
      claimName: 982da85fd0bd6c7ffc6cbe399b68888033ebebb95bd7580d6768d3434b4288b6
  - name: 85b442e55f8c1a847df7a75c2c964051ca5333af424a3b309aad5f82fb448be2-pvc
    persistentVolumeClaim:
      claimName: 85b442e55f8c1a847df7a75c2c964051ca5333af424a3b309aad5f82fb448be2

